// Safe handling of uploaded files.
//
// The browser sends files as base64 data URLs. We decode them, check the real
// file signature (never the name or declared type), save under a random name we
// generate ourselves, and hand back a path. SVG is rejected on purpose because
// it can carry scripts.

import fs from "fs";
import path from "path";
import { randomUUID } from "crypto";
import { fileURLToPath } from "url";
import { HttpError } from "./security.js";
import { PRIVATE_UPLOADS, PUBLIC_UPLOADS } from "./db.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const EXTENSIONS = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "application/pdf": "pdf",
};

export const MAX_IMAGE_BYTES = 4 * 1024 * 1024;
export const MAX_POP_BYTES = 6 * 1024 * 1024;

export function sniffType(buffer) {
  if (buffer.length < 12) return null;
  if (buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff) return "image/jpeg";
  if (buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "image/png";
  if (buffer.subarray(0, 4).toString("ascii") === "GIF8") return "image/gif";
  if (buffer.subarray(0, 4).toString("ascii") === "RIFF" && buffer.subarray(8, 12).toString("ascii") === "WEBP") return "image/webp";
  if (buffer.subarray(0, 5).toString("ascii") === "%PDF-") return "application/pdf";
  return null;
}

function decode(dataUrl, maxBytes) {
  const match = /^data:([\w/+.-]+);base64,([A-Za-z0-9+/=\r\n]+)$/.exec(String(dataUrl || ""));
  if (!match) throw new HttpError(400, "That file could not be read.");
  const buffer = Buffer.from(match[2], "base64");
  if (buffer.length === 0) throw new HttpError(400, "That file is empty.");
  if (buffer.length > maxBytes) {
    throw new HttpError(413, `That file is too large (maximum ${Math.round(maxBytes / 1024 / 1024)} MB).`);
  }
  return buffer;
}

export function savePublicImage(dataUrl) {
  const buffer = decode(dataUrl, MAX_IMAGE_BYTES);
  const type = sniffType(buffer);
  if (!type || type === "application/pdf") throw new HttpError(400, "Please upload a JPG, PNG, WebP or GIF image.");
  const name = `${randomUUID()}.${EXTENSIONS[type]}`;
  fs.writeFileSync(path.join(PUBLIC_UPLOADS, name), buffer);
  return `/uploads/public/${name}`;
}

export function savePrivateProof(dataUrl) {
  const buffer = decode(dataUrl, MAX_POP_BYTES);
  const type = sniffType(buffer);
  if (!type || type === "image/gif") throw new HttpError(400, "Please upload a PDF, JPG or PNG file.");
  const storedName = `${randomUUID()}.${EXTENSIONS[type]}`;
  fs.writeFileSync(path.join(PRIVATE_UPLOADS, storedName), buffer, { mode: 0o600 });
  return { storedName, type, size: buffer.length };
}

export function privateFilePath(storedName) {
  // stored names are generated by us, but never trust what's in a database row blindly
  if (!/^[A-Za-z0-9-]+\.(jpg|png|pdf)$/.test(storedName)) return null;
  return path.join(PRIVATE_UPLOADS, storedName);
}

export function deleteFileQuietly(filePath) {
  try {
    fs.unlinkSync(filePath);
  } catch {
    // already gone
  }
}

// Remove an uploaded public image once nothing references it. Built-in seed
// and default images are never deleted.
export function deletePublicImage(urlPath) {
  const match = /^\/uploads\/public\/([A-Za-z0-9._-]+)$/.exec(urlPath || "");
  if (!match) return;
  if (match[1].startsWith("seed-") || match[1].startsWith("default-")) return;
  deleteFileQuietly(path.join(PUBLIC_UPLOADS, match[1]));
}

// Make sure the built-in images exist in the uploads folder.
export function ensureSeedAssets() {
  const source = path.join(__dirname, "seed-assets");
  if (!fs.existsSync(source)) return;
  for (const file of fs.readdirSync(source)) {
    const target = path.join(PUBLIC_UPLOADS, file);
    if (!fs.existsSync(target)) fs.copyFileSync(path.join(source, file), target);
  }
}

export function uploadsSizeBytes() {
  let total = 0;
  for (const dir of [PUBLIC_UPLOADS, PRIVATE_UPLOADS]) {
    for (const file of fs.readdirSync(dir)) {
      try {
        total += fs.statSync(path.join(dir, file)).size;
      } catch {
        // ignore
      }
    }
  }
  return total;
}
